[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.normal]
family = "JetBrainsMonoNFP"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window]
opacity = 0.95
title = "Terminal"

[window.padding]
x = 10
y = 10

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.primary]
background = '0x1a1b26'
foreground = '0xc0caf5'

[colors.normal]
black = '0x1a1b26'
red = '0xef6155'
green = '0x9ece6a'
yellow = '0xe0af68'
blue = '0x7aa2f7'
magenta = '0xae9ac8'
cyan = '0x7dcfff'
white = '0xa9b1d6'

[colors.bright]
black = '0x414868'
red = '0xf7768e'
green = '0x9ece6a'
yellow = '0xe0af68'
blue = '0x7aa2f7'
magenta = '0xae9ac8'
cyan = '0x7dcfff'
white = '0xc0caf5'
